on: push
  branches:
    - main
name: FTP Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 62.72.50.238
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: 21
        protocol: ftp
